apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: parijatkasbekar/capstonedataclustering:v0.0.2
        ports:
        - containerPort: 8002 

---

apiVersion: v1
kind: Service
metadata:
  name: capstone-service
spec:
  selector:
    app: capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: LoadBalancer